"use client"

import type React from "react"
import { useState, useEffect, useCallback, useMemo, useRef } from "react"
import {
  ArrowLeft,
  ArrowRight,
  Search,
  Filter,
  Plus,
  Sparkles,
  GripVertical,
  Edit3,
  Trash2,
  Copy,
  MoreVertical,
  ChevronDown,
  CheckCircle,
  Info,
  Save,
  X,
  Building2,
  MapPin,
  Phone,
  Clock,
  DollarSign,
  FolderOpen,
  List,
  LayoutGrid,
  AlignJustify,
  Loader2,
  EyeOff,
  Eye,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import type { BusinessData } from "./business-details-form"
import { WhatsAppConnectionModal } from "./whatsapp-connection-modal"

// Types
interface QAItem {
  id: string
  question: string
  answer: string
  category: string
  language: string
  isAutoGenerated: boolean
  isEnabled: boolean
  priority: number
  order: number
}

interface Category {
  id: string
  name: string
  icon: React.ReactNode
  count: number
  isExpanded: boolean
}

interface AIPreviewProps {
  businessData: BusinessData
  agentId?: string
  onBack: () => void
  onContinue: (qaItems: QAItem[]) => void
  onEditDetails: () => void
}

// Category icons mapping
const categoryIcons: Record<string, React.ReactNode> = {
  "basic-info": <Building2 className="w-5 h-5" />,
  "working-hours": <Clock className="w-5 h-5" />,
  location: <MapPin className="w-5 h-5" />,
  services: <DollarSign className="w-5 h-5" />,
  booking: <Phone className="w-5 h-5" />,
  payment: <DollarSign className="w-5 h-5" />,
  features: <Sparkles className="w-5 h-5" />,
  policies: <Info className="w-5 h-5" />,
  other: <FolderOpen className="w-5 h-5" />,
}

// Generate Q&A based on business data
function generateQAFromBusinessData(data: BusinessData): QAItem[] {
  const qaItems: QAItem[] = []
  let order = 1

  // Basic Information
  qaItems.push({
    id: `qa-${order}`,
    question: "What is the name of your clinic?",
    answer: `Our clinic is called ${data.clinicName}. We're located in ${data.city}, ${data.country}.`,
    category: "basic-info",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 5,
    order: order++,
  })

  if (data.doctorNames.length > 0) {
    const doctorList = data.doctorNames.filter((n) => n.trim()).join(", ")
    qaItems.push({
      id: `qa-${order}`,
      question: "Who are the doctors at your clinic?",
      answer: `Our clinic is led by ${doctorList}. ${data.yearsOfExperience ? `With ${data.yearsOfExperience} years of experience in dentistry.` : ""}`,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 5,
      order: order++,
    })
  }

  const enabledServices = data.services.filter((s) => s.enabled)
  if (enabledServices.length > 0) {
    const topServices = enabledServices
      .slice(0, 5)
      .map((s) => s.name)
      .join(", ")
    qaItems.push({
      id: `qa-${order}`,
      question: "What services do you offer?",
      answer: `We offer a comprehensive range of dental services including ${topServices}. You can view our complete service list and pricing by asking about specific treatments.`,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 5,
      order: order++,
    })
  }

  if (data.features.languages && data.features.languages.length > 0) {
    qaItems.push({
      id: `qa-${order}`,
      question: "What languages do you speak?",
      answer: `Our team speaks ${data.features.languages.join(", ")}. We can assist you in your preferred language.`,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  if (data.aboutClinic) {
    qaItems.push({
      id: `qa-${order}`,
      question: "Tell me about your clinic",
      answer: data.aboutClinic,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  if (data.yearsOfExperience) {
    qaItems.push({
      id: `qa-${order}`,
      question: "How many years of experience do you have?",
      answer: `${data.doctorNames[0] || "Our team"} has been practicing dentistry for ${data.yearsOfExperience} years.`,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  // Working Hours
  const workingDays = Object.entries(data.workingHours)
    .filter(([_, hours]) => hours.isOpen)
    .map(([day, hours]) => `${day}: ${hours.shifts.map((s) => `${s.from} - ${s.to}`).join(", ")}`)

  qaItems.push({
    id: `qa-${order}`,
    question: "What are your working hours?",
    answer: `We're open:\n${workingDays.map((d) => `• ${d}`).join("\n")}`,
    category: "working-hours",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 5,
    order: order++,
  })

  const saturdayHours = data.workingHours.Saturday
  const sundayHours = data.workingHours.Sunday
  qaItems.push({
    id: `qa-${order}`,
    question: "Are you open on weekends?",
    answer: `${saturdayHours.isOpen ? `Yes, we're open on Saturday from ${saturdayHours.shifts[0]?.from || "9:00"} to ${saturdayHours.shifts[0]?.to || "14:00"}.` : "We're closed on Saturdays."} ${sundayHours.isOpen ? `We're also open on Sunday from ${sundayHours.shifts[0]?.from} to ${sundayHours.shifts[0]?.to}.` : "We're closed on Sundays."}`,
    category: "working-hours",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  const weekdayHours = data.workingHours.Monday
  qaItems.push({
    id: `qa-${order}`,
    question: "What time do you close?",
    answer: `We close at ${weekdayHours.shifts[0]?.to || "18:00"} on weekdays${saturdayHours.isOpen ? ` and ${saturdayHours.shifts[0]?.to || "14:00"} on Saturdays` : ""}.`,
    category: "working-hours",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "Are you open today?",
    answer:
      "I can check our schedule for you. Our working hours vary by day - please tell me which day you're asking about, or I can check today's date for you.",
    category: "working-hours",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  // Location & Directions
  qaItems.push({
    id: `qa-${order}`,
    question: "Where is your clinic located?",
    answer: `We're located at ${data.address}, ${data.city}, ${data.country}.`,
    category: "location",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 5,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "How do I get to your clinic?",
    answer: `Our address is ${data.address}, ${data.city}.${data.googleMapsLink ? ` Here's our location on Google Maps: ${data.googleMapsLink}` : ""}`,
    category: "location",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "What city are you in?",
    answer: `We're located in ${data.city}, ${data.country}.`,
    category: "location",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  if (data.googleMapsLink) {
    qaItems.push({
      id: `qa-${order}`,
      question: "Do you have a map or directions?",
      answer: `Yes! Here's our location on Google Maps: ${data.googleMapsLink}`,
      category: "location",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  // Services & Pricing - one per service
  enabledServices.forEach((service) => {
    let priceText = ""
    const sym = data.currency.symbol
    switch (service.pricing.type) {
      case "fixed":
        priceText = `${sym}${service.pricing.value} ${data.currency.code}`
        break
      case "range":
        priceText = `between ${sym}${service.pricing.min} - ${sym}${service.pricing.max} ${data.currency.code}`
        break
      case "starting_from":
        priceText = `from ${sym}${service.pricing.value} ${data.currency.code}`
        break
      case "on_request":
        priceText = "available on request - please contact us for a quote"
        break
    }

    qaItems.push({
      id: `qa-${order}`,
      question: `How much does ${service.name.toLowerCase()} cost?`,
      answer: `${service.name} costs ${priceText}.${service.description ? ` ${service.description}` : ""}${service.duration ? ` This typically takes ${service.duration}.` : ""}`,
      category: "services",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 5,
      order: order++,
    })
  })

  // Booking & Appointments
  qaItems.push({
    id: `qa-${order}`,
    question: "How do I book an appointment?",
    answer: `To book an appointment, please provide me with:\n• Your full name\n• Preferred date and time\n• Phone number\n• Reason for visit\n\nI'll pass your request to our reception team who will confirm your appointment.`,
    category: "booking",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 5,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "Can I book an appointment now?",
    answer:
      "Yes! Please tell me:\n1. Your full name\n2. What date and time you prefer\n3. Your phone number\n4. What you need (consultation, cleaning, specific treatment, etc.)",
    category: "booking",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 5,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "Do I need an appointment?",
    answer: "Yes, we work by appointment to ensure you receive our full attention. You can book through this chat!",
    category: "booking",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  if (data.bookingPolicy) {
    qaItems.push({
      id: `qa-${order}`,
      question: "What if I need to cancel?",
      answer: data.bookingPolicy,
      category: "booking",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  const hasEmergency = data.features.patientCare?.includes("Emergency appointments available")
  qaItems.push({
    id: `qa-${order}`,
    question: "Do you accept walk-ins?",
    answer: hasEmergency
      ? "We accept emergency walk-ins. For regular appointments, booking in advance is recommended."
      : "We work by appointment. Please book ahead to ensure availability.",
    category: "booking",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "How far in advance should I book?",
    answer:
      "We recommend booking at least 1-2 weeks in advance for regular appointments. However, we can often accommodate urgent cases sooner.",
    category: "booking",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "Can I change my appointment time?",
    answer:
      "Yes, please provide your name and current appointment time, and let me know when you'd prefer to reschedule.",
    category: "booking",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  qaItems.push({
    id: `qa-${order}`,
    question: "What should I bring to my appointment?",
    answer: "Please bring:\n• Valid ID\n• Previous dental records (if available)\n• List of current medications",
    category: "booking",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 4,
    order: order++,
  })

  // Contact
  qaItems.push({
    id: `qa-${order}`,
    question: "What is your phone number?",
    answer: `You can reach us at ${data.phoneNumber}.${data.whatsappNumber && data.whatsappNumber !== data.phoneNumber ? ` Our WhatsApp number is ${data.whatsappNumber}.` : ""}`,
    category: "basic-info",
    language: "en",
    isAutoGenerated: true,
    isEnabled: true,
    priority: 5,
    order: order++,
  })

  if (data.email) {
    qaItems.push({
      id: `qa-${order}`,
      question: "What is your email address?",
      answer: `You can email us at ${data.email}.`,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  if (data.website) {
    qaItems.push({
      id: `qa-${order}`,
      question: "Do you have a website?",
      answer: `Yes! Visit our website at ${data.website} for more information.`,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  // Special Features based on selected features
  if (hasEmergency) {
    qaItems.push({
      id: `qa-${order}`,
      question: "Do you handle dental emergencies?",
      answer: `Yes! We accept emergency patients. If you're experiencing severe pain, trauma, or an abscess, please call us immediately at ${data.phoneNumber} or visit during our working hours.`,
      category: "features",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 5,
      order: order++,
    })
  }

  if (data.features.patientCare?.includes("Children's dentistry (ages 3+)")) {
    qaItems.push({
      id: `qa-${order}`,
      question: "Do you treat children?",
      answer:
        "Yes, we treat children starting from age 3. We have experience making dental visits comfortable and stress-free for kids.",
      category: "features",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  if (data.features.patientCare?.includes("Sedation dentistry")) {
    qaItems.push({
      id: `qa-${order}`,
      question: "Do you offer sedation?",
      answer:
        "Yes, we offer sedation dentistry for patients who experience dental anxiety or require lengthy procedures.",
      category: "features",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  if (data.features.technology && data.features.technology.length > 0) {
    qaItems.push({
      id: `qa-${order}`,
      question: "What technology do you use?",
      answer: `We use modern dental technology including ${data.features.technology.join(", ")}.`,
      category: "features",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  if (data.features.specializations && data.features.specializations.length > 0) {
    qaItems.push({
      id: `qa-${order}`,
      question: "What are your specializations?",
      answer: `We specialize in ${data.features.specializations.join(", ")}.`,
      category: "features",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  if (data.certifications && data.certifications.length > 0) {
    qaItems.push({
      id: `qa-${order}`,
      question: "What certifications do you have?",
      answer: `Our team holds certifications in ${data.certifications.filter((c) => c.trim()).join(", ")}.`,
      category: "basic-info",
      language: "en",
      isAutoGenerated: true,
      isEnabled: true,
      priority: 4,
      order: order++,
    })
  }

  return qaItems
}

const CATEGORIES: Category[] = [
  { id: "basic-info", name: "Basic Information", icon: categoryIcons["basic-info"], count: 0, isExpanded: false },
  { id: "working-hours", name: "Working Hours", icon: categoryIcons["working-hours"], count: 0, isExpanded: false },
  { id: "location", name: "Location & Directions", icon: categoryIcons["location"], count: 0, isExpanded: false },
  { id: "services", name: "Services & Pricing", icon: categoryIcons["services"], count: 0, isExpanded: false },
  { id: "booking", name: "Booking & Appointments", icon: categoryIcons["booking"], count: 0, isExpanded: false },
  { id: "features", name: "Special Features", icon: categoryIcons["features"], count: 0, isExpanded: false },
  { id: "other", name: "Other", icon: categoryIcons["other"], count: 0, isExpanded: false },
]

export function AIPreview({ businessData, agentId, onBack, onContinue, onEditDetails }: AIPreviewProps) {
  const [qaItems, setQaItems] = useState<QAItem[]>([])
  const [categories, setCategories] = useState<Category[]>(CATEGORIES)
  const [searchQuery, setSearchQuery] = useState("")
  const [selectedCategories, setSelectedCategories] = useState<string[]>([])
  const [viewMode, setViewMode] = useState<"list" | "card" | "compact">("list")
  const [sortBy, setSortBy] = useState<"category" | "priority" | "alphabetical">("category")
  const [selectedItems, setSelectedItems] = useState<string[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [editingItem, setEditingItem] = useState<QAItem | null>(null)
  const [isSaving, setIsSaving] = useState(false)
  const [lastSaved, setLastSaved] = useState<Date | null>(null)
  const [showCategoryFilter, setShowCategoryFilter] = useState(false)
  const [showConnectModal, setShowConnectModal] = useState(false)

  const topRef = useRef<HTMLDivElement>(null)

  // New Q&A form state
  const [newQuestion, setNewQuestion] = useState("")
  const [newAnswer, setNewAnswer] = useState("")
  const [newCategory, setNewCategory] = useState("other")
  const [newPriority, setNewPriority] = useState(5)

  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" })
  }, [])

  // Generate Q&A on mount
  useEffect(() => {
    const generated = generateQAFromBusinessData(businessData)
    setQaItems(generated)
  }, [businessData])

  // Update category counts
  useEffect(() => {
    const counts = qaItems.reduce(
      (acc, item) => {
        acc[item.category] = (acc[item.category] || 0) + 1
        return acc
      },
      {} as Record<string, number>,
    )

    setCategories((prev) =>
      prev.map((cat) => ({
        ...cat,
        count: counts[cat.id] || 0,
      })),
    )
  }, [qaItems])

  // Auto-save
  useEffect(() => {
    const timer = setTimeout(() => {
      if (qaItems.length > 0) {
        handleAutoSave()
      }
    }, 5000)
    return () => clearTimeout(timer)
  }, [qaItems])

  const handleAutoSave = useCallback(() => {
    localStorage.setItem("qa_items_draft", JSON.stringify(qaItems))
    setLastSaved(new Date())
  }, [qaItems])

  // Filter and sort Q&A items
  const filteredItems = useMemo(() => {
    let items = [...qaItems]

    // Search filter
    if (searchQuery) {
      const query = searchQuery.toLowerCase()
      items = items.filter(
        (item) => item.question.toLowerCase().includes(query) || item.answer.toLowerCase().includes(query),
      )
    }

    // Category filter
    if (selectedCategories.length > 0) {
      items = items.filter((item) => selectedCategories.includes(item.category))
    }

    // Sort
    switch (sortBy) {
      case "priority":
        items.sort((a, b) => b.priority - a.priority)
        break
      case "alphabetical":
        items.sort((a, b) => a.question.localeCompare(b.question))
        break
      case "category":
      default:
        items.sort((a, b) => a.order - b.order)
        break
    }

    return items
  }, [qaItems, searchQuery, selectedCategories, sortBy])

  // Group items by category
  const groupedItems = useMemo(() => {
    const groups: Record<string, QAItem[]> = {}
    filteredItems.forEach((item) => {
      if (!groups[item.category]) {
        groups[item.category] = []
      }
      groups[item.category].push(item)
    })
    return groups
  }, [filteredItems])

  // Handlers
  const handleToggleCategory = (categoryId: string) => {
    setCategories((prev) => prev.map((cat) => (cat.id === categoryId ? { ...cat, isExpanded: !cat.isExpanded } : cat)))
  }

  const handleCategoryFilterToggle = (categoryId: string) => {
    setSelectedCategories((prev) =>
      prev.includes(categoryId) ? prev.filter((c) => c !== categoryId) : [...prev, categoryId],
    )
  }

  const handleSelectItem = (itemId: string) => {
    setSelectedItems((prev) => (prev.includes(itemId) ? prev.filter((id) => id !== itemId) : [...prev, itemId]))
  }

  const handleSelectAll = () => {
    if (selectedItems.length === filteredItems.length) {
      setSelectedItems([])
    } else {
      setSelectedItems(filteredItems.map((item) => item.id))
    }
  }

  const handleDeleteItem = (itemId: string) => {
    setQaItems((prev) => prev.filter((item) => item.id !== itemId))
    setSelectedItems((prev) => prev.filter((id) => id !== itemId))
  }

  const handleDeleteSelected = () => {
    setQaItems((prev) => prev.filter((item) => !selectedItems.includes(item.id)))
    setSelectedItems([])
  }

  const handleDuplicateItem = (item: QAItem) => {
    const newItem: QAItem = {
      ...item,
      id: `qa-${Date.now()}`,
      question: `${item.question} (copy)`,
      isAutoGenerated: false,
      order: qaItems.length + 1,
    }
    setQaItems((prev) => [...prev, newItem])
  }

  const handleToggleEnabled = (itemId: string) => {
    setQaItems((prev) => prev.map((item) => (item.id === itemId ? { ...item, isEnabled: !item.isEnabled } : item)))
  }

  const handleOpenEdit = (item: QAItem) => {
    setEditingItem(item)
    setNewQuestion(item.question)
    setNewAnswer(item.answer)
    setNewCategory(item.category)
    setNewPriority(item.priority)
    setShowAddModal(true)
  }

  const handleOpenAdd = () => {
    setEditingItem(null)
    setNewQuestion("")
    setNewAnswer("")
    setNewCategory("other")
    setNewPriority(5)
    setShowAddModal(true)
  }

  // Moved handleSaveQA to update editingItem directly and then call setQaItems
  const handleSaveQA = () => {
    if (!newQuestion.trim() || !newAnswer.trim()) return

    setQaItems((prevQaItems) => {
      if (editingItem) {
        return prevQaItems.map((item) =>
          item.id === editingItem.id
            ? {
                ...item,
                question: newQuestion,
                answer: newAnswer,
                category: newCategory,
                priority: newPriority,
                isAutoGenerated: false,
              }
            : item,
        )
      } else {
        const newItem: QAItem = {
          id: `qa-${Date.now()}`,
          question: newQuestion,
          answer: newAnswer,
          category: newCategory,
          language: "en",
          isAutoGenerated: false,
          isEnabled: true,
          priority: newPriority,
          order: prevQaItems.length + 1,
        }
        return [...prevQaItems, newItem]
      }
    })

    setShowAddModal(false)
    setEditingItem(null)
  }

  // Placeholder functions for handleUpdateItem and handleAddItem, as they were removed from the original code.
  // In a real scenario, you'd implement these or ensure handleSaveQA covers their functionality.
  const handleUpdateItem = (itemToUpdate: QAItem) => {
    // This function would typically update the state with the edited item.
    // For now, it's handled within handleSaveQA when editingItem is present.
  }

  const handleAddItem = () => {
    // This function would typically add a new item to the state.
    // For now, it's handled within handleSaveQA when editingItem is null.
  }

  const handleSaveDraft = async () => {
    setIsSaving(true)
    handleAutoSave()
    await new Promise((resolve) => setTimeout(resolve, 500))
    setIsSaving(false)
  }

  const handleConfirm = () => {
    onContinue(qaItems.filter((item) => item.isEnabled))
  }

  const handleConnectionSuccess = (phoneNumber: string) => {
    onContinue(qaItems)
  }

  const handleConfirmAndConnect = () => {
    setShowConnectModal(true)
  }

  const totalQA = qaItems.length
  const categoryCount = categories.filter((c) => c.count > 0).length
  const enabledServices = businessData.services.filter((s) => s.enabled).length

  return (
    <div ref={topRef} className="w-full px-4 sm:px-6 lg:px-8 py-8">
      {/* Existing breadcrumb and header */}
      <nav className="text-sm text-gray-500 mb-6">
        <span>WhatsApp Agent</span>
        <span className="mx-2">&gt;</span>
        <span>Create Agent</span>
        <span className="mx-2">&gt;</span>
        <span className="text-purple-600 font-medium">Preview AI</span>
      </nav>

      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-6 mb-8">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <div className="w-10 h-10 rounded-lg bg-purple-100 flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-purple-600" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Preview AI Responses</h1>
              <p className="text-gray-600">{qaItems.length} Q&A pairs generated</p>
            </div>
          </div>
        </div>

        {/* Business Summary Card */}
        <div className="bg-white border rounded-lg p-4 min-w-[280px]">
          <div className="flex items-start justify-between mb-3">
            <div className="flex items-center gap-2">
              <Building2 className="w-4 h-4 text-gray-400" />
              <span className="font-medium text-gray-900">{businessData.clinicName}</span>
            </div>
            <button onClick={onEditDetails} className="text-purple-600 hover:text-purple-700 text-sm font-medium">
              Edit
            </button>
          </div>
          <div className="space-y-1 text-sm text-gray-600">
            <div className="flex items-center gap-2">
              <MapPin className="w-3 h-3" />
              <span>
                {businessData.city}, {businessData.country}
              </span>
            </div>
            <div className="flex items-center gap-2">
              <Phone className="w-3 h-3" />
              <span>{businessData.phoneNumber}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-3 gap-4 mb-8">
        <div className="bg-white border rounded-lg p-4 text-center">
          <p className="text-3xl font-bold text-purple-600">{qaItems.length}</p>
          <p className="text-sm text-gray-600">AI Responses</p>
        </div>
        <div className="bg-white border rounded-lg p-4 text-center">
          <p className="text-3xl font-bold text-purple-600">{categories.filter((c) => c.count > 0).length}</p>
          <p className="text-sm text-gray-600">Categories</p>
        </div>
        <div className="bg-white border rounded-lg p-4 text-center">
          <p className="text-3xl font-bold text-purple-600">1</p>
          <p className="text-sm text-gray-600">Language</p>
        </div>
      </div>

      {/* Filters & Search */}
      <div className="bg-white border rounded-lg p-4 mb-6">
        <div className="flex flex-col sm:flex-row gap-4">
          {/* Search */}
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
            <Input
              placeholder="Search questions or answers..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>

          {/* Category Filter */}
          <div className="relative">
            <button
              onClick={() => setShowCategoryFilter(!showCategoryFilter)}
              className="flex items-center gap-2 px-4 py-2 border rounded-lg hover:bg-gray-50"
            >
              <Filter className="w-4 h-4" />
              <span>Categories</span>
              {selectedCategories.length > 0 && (
                <span className="bg-purple-100 text-purple-600 text-xs px-2 py-0.5 rounded-full">
                  {selectedCategories.length}
                </span>
              )}
              <ChevronDown className="w-4 h-4" />
            </button>

            {showCategoryFilter && (
              <>
                <div className="fixed inset-0 z-10" onClick={() => setShowCategoryFilter(false)} />
                <div className="absolute right-0 top-full mt-2 bg-white rounded-lg border shadow-lg p-4 z-20 min-w-[200px]">
                  {categories.map((cat) => (
                    <label
                      key={cat.id}
                      className="flex items-center gap-2 py-2 cursor-pointer hover:bg-gray-50 px-2 rounded"
                    >
                      <Checkbox
                        checked={selectedCategories.includes(cat.id)}
                        onCheckedChange={(checked) => {
                          if (checked) {
                            setSelectedCategories([...selectedCategories, cat.id])
                          } else {
                            setSelectedCategories(selectedCategories.filter((id) => id !== cat.id))
                          }
                        }}
                      />
                      <span className="flex-1 text-sm">{cat.name}</span>
                      <span className="text-xs text-gray-400">{cat.count}</span>
                    </label>
                  ))}
                </div>
              </>
            )}
          </div>

          {/* View Mode */}
          <div className="flex items-center gap-1 border rounded-lg p-1">
            <button
              onClick={() => setViewMode("list")}
              className={`p-2 rounded ${viewMode === "list" ? "bg-purple-100 text-purple-600" : "text-gray-400 hover:text-gray-600"}`}
            >
              <List className="w-4 h-4" />
            </button>
            <button
              onClick={() => setViewMode("card")}
              className={`p-2 rounded ${viewMode === "card" ? "bg-purple-100 text-purple-600" : "text-gray-400 hover:text-gray-600"}`}
            >
              <LayoutGrid className="w-4 h-4" />
            </button>
            <button
              onClick={() => setViewMode("compact")}
              className={`p-2 rounded ${viewMode === "compact" ? "bg-purple-100 text-purple-600" : "text-gray-400 hover:text-gray-600"}`}
            >
              <AlignJustify className="w-4 h-4" />
            </button>
          </div>

          {/* Add Custom Q&A */}
          <Button onClick={handleOpenAdd} className="bg-purple-600 hover:bg-purple-700">
            <Plus className="w-4 h-4 mr-2" />
            Add Q&A
          </Button>
        </div>
      </div>

      {/* Q&A List by Category */}
      <div className="space-y-6 mb-8">
        {categories
          .filter((cat) => cat.count > 0)
          .map((category) => {
            const categoryItems = groupedItems[category.id] || []
            if (categoryItems.length === 0) return null

            return (
              <div key={category.id} className="bg-white border rounded-lg overflow-hidden">
                {/* Category Header */}
                <button
                  onClick={() => handleToggleCategory(category.id)}
                  className={`w-full flex items-center justify-between px-6 py-4 transition-colors ${
                    category.isExpanded ? "bg-purple-50" : "bg-gray-50 hover:bg-gray-100"
                  }`}
                  aria-expanded={category.isExpanded}
                  aria-controls={`category-${category.id}`}
                >
                  <div className="flex items-center gap-3">
                    <div className="text-purple-600">{category.icon}</div>
                    <span className="font-medium text-gray-900">{category.name}</span>
                    <span className="bg-purple-100 text-purple-600 text-xs px-2 py-0.5 rounded-full">
                      {categoryItems.length}
                    </span>
                  </div>
                  <ChevronDown
                    className={`w-5 h-5 text-gray-400 transition-transform duration-300 ${
                      category.isExpanded ? "rotate-180" : ""
                    }`}
                  />
                </button>

                {/* Category Items */}
                <div
                  id={`category-${category.id}`}
                  className={`transition-all duration-300 ease-in-out overflow-hidden ${
                    category.isExpanded ? "max-h-[5000px] opacity-100" : "max-h-0 opacity-0"
                  }`}
                >
                  <div className="divide-y">
                    {categoryItems.map((item) => (
                      <QACard
                        key={item.id}
                        item={item}
                        viewMode={viewMode}
                        categoryName={category.name}
                        isSelected={selectedItems.includes(item.id)}
                        onSelect={() => {
                          if (selectedItems.includes(item.id)) {
                            setSelectedItems(selectedItems.filter((id) => id !== item.id))
                          } else {
                            setSelectedItems([...selectedItems, item.id])
                          }
                        }}
                        onEdit={() => handleOpenEdit(item)}
                        onDelete={() => handleDeleteItem(item.id)}
                        onDuplicate={() => handleDuplicateItem(item)}
                        onToggleEnabled={() => handleToggleEnabled(item.id)}
                      />
                    ))}
                  </div>
                </div>
              </div>
            )
          })}
      </div>

      {/* Empty State */}
      {filteredItems.length === 0 && (
        <div className="text-center py-12 bg-white rounded-xl border">
          <Search className="w-12 h-12 text-gray-300 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No matches found</h3>
          <p className="text-gray-500 mb-4">Try different keywords or clear your filters.</p>
          <Button
            variant="outline"
            onClick={() => {
              setSearchQuery("")
              setSelectedCategories([])
            }}
          >
            Clear filters
          </Button>
        </div>
      )}

      <div className="bg-gradient-to-br from-purple-600 to-purple-700 rounded-2xl p-8 text-white mb-8">
        <div className="text-center mb-6">
          <div className="w-16 h-16 bg-green-500 rounded-full flex items-center justify-center mx-auto mb-4">
            <CheckCircle className="w-10 h-10 text-white" />
          </div>
          <h2 className="text-2xl font-bold mb-2">Ready to Connect Your WhatsApp?</h2>
          <p className="text-purple-100">
            Your AI agent is configured with {qaItems.length} intelligent responses. Connect your WhatsApp Business
            number to start automating customer conversations.
          </p>
        </div>

        {/* Checklist */}
        <div className="space-y-3 mb-6">
          <div className="flex items-center gap-3">
            <CheckCircle className="w-5 h-5 text-green-400" />
            <span>Business details configured</span>
          </div>
          <div className="flex items-center gap-3">
            <CheckCircle className="w-5 h-5 text-green-400" />
            <span>{qaItems.length} AI responses generated</span>
          </div>
          <div className="flex items-center gap-3">
            <CheckCircle className="w-5 h-5 text-green-400" />
            <span>Services and pricing set</span>
          </div>
        </div>

        {/* Info Banner */}
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-6">
          <div className="flex items-start gap-3">
            <Info className="w-5 h-5 text-blue-600 mt-0.5" />
            <p className="text-sm text-blue-700">
              After connecting WhatsApp, your AI agent will start responding to customer messages automatically. You can
              edit responses anytime.
            </p>
          </div>
        </div>
      </div>

      <div className="bg-white border-t rounded-t-xl shadow-lg -mx-4 sm:-mx-6 lg:-mx-8 px-4 sm:px-6 lg:px-8 py-4">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <Button variant="ghost" onClick={onBack} className="text-gray-600 hover:text-gray-900">
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Details
          </Button>

          <div className="flex items-center gap-3">
            <Button
              variant="outline"
              onClick={handleSaveDraft}
              disabled={isSaving}
              className="border-purple-600 text-purple-600 hover:bg-purple-50 bg-transparent"
            >
              {isSaving ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Save className="w-4 h-4 mr-2" />}
              Save Draft
            </Button>

            <Button onClick={handleConfirmAndConnect} className="bg-purple-600 hover:bg-purple-700">
              Confirm & Connect WhatsApp
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
        </div>

        {lastSaved && (
          <p className="text-xs text-gray-400 text-center mt-2">Last saved: {lastSaved.toLocaleTimeString()}</p>
        )}
      </div>

      {/* Add/Edit Modal */}
      {(showAddModal || editingItem) && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div
            className="absolute inset-0 bg-black/50"
            onClick={() => {
              setShowAddModal(false)
              setEditingItem(null)
            }}
          />
          <div className="relative bg-white rounded-xl shadow-xl w-full max-w-lg p-6">
            <button
              onClick={() => {
                setShowAddModal(false)
                setEditingItem(null)
              }}
              className="absolute top-4 right-4 p-2 hover:bg-gray-100 rounded-full"
            >
              <X className="w-5 h-5" />
            </button>

            <h2 className="text-xl font-bold mb-6">{editingItem ? "Edit Q&A" : "Add Custom Q&A"}</h2>

            <div className="space-y-4">
              <div>
                <Label>Question</Label>
                <Textarea
                  placeholder="Enter the question..."
                  value={editingItem ? editingItem.question : newQuestion}
                  onChange={(e) => {
                    if (editingItem) {
                      setEditingItem({ ...editingItem, question: e.target.value })
                    } else {
                      setNewQuestion(e.target.value)
                    }
                  }}
                  className="mt-1"
                />
              </div>

              <div>
                <Label>Answer</Label>
                <Textarea
                  placeholder="Enter the answer..."
                  value={editingItem ? editingItem.answer : newAnswer}
                  onChange={(e) => {
                    if (editingItem) {
                      setEditingItem({ ...editingItem, answer: e.target.value })
                    } else {
                      setNewAnswer(e.target.value)
                    }
                  }}
                  className="mt-1 min-h-[120px]"
                />
              </div>

              <div>
                <Label>Category</Label>
                <select
                  value={editingItem ? editingItem.category : newCategory}
                  onChange={(e) => {
                    if (editingItem) {
                      setEditingItem({ ...editingItem, category: e.target.value })
                    } else {
                      setNewCategory(e.target.value)
                    }
                  }}
                  className="w-full mt-1 px-3 py-2 border rounded-lg"
                >
                  {categories.map((cat) => (
                    <option key={cat.id} value={cat.id}>
                      {cat.name}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <Label>Priority (1-10)</Label>
                <Input
                  type="number"
                  min={1}
                  max={10}
                  value={editingItem ? editingItem.priority : newPriority}
                  onChange={(e) => {
                    const val = Number.parseInt(e.target.value)
                    if (!isNaN(val)) {
                      if (editingItem) {
                        setEditingItem({ ...editingItem, priority: val })
                      } else {
                        setNewPriority(val)
                      }
                    }
                  }}
                  className="mt-1"
                />
              </div>
            </div>

            <div className="flex justify-end gap-3 mt-6">
              <Button
                variant="outline"
                onClick={() => {
                  setShowAddModal(false)
                  setEditingItem(null)
                }}
              >
                Cancel
              </Button>
              <Button onClick={handleSaveQA} className="bg-purple-600 hover:bg-purple-700">
                {editingItem ? "Save Changes" : "Add Q&A"}
              </Button>
            </div>
          </div>
        </div>
      )}

      <WhatsAppConnectionModal
        isOpen={showConnectModal}
        onClose={() => setShowConnectModal(false)}
        onSuccess={handleConnectionSuccess}
        agentId={agentId || ""}
      />
    </div>
  )
}

// Q&A Card Component
interface QACardProps {
  item: QAItem
  viewMode: "list" | "card" | "compact"
  categoryName: string
  isSelected: boolean
  onSelect: () => void
  onEdit: () => void
  onDelete: () => void
  onDuplicate: () => void
  onToggleEnabled: () => void
}

function QACard({
  item,
  viewMode,
  categoryName,
  isSelected,
  onSelect,
  onEdit,
  onDelete,
  onDuplicate,
  onToggleEnabled,
}: QACardProps) {
  const [showMenu, setShowMenu] = useState(false)

  if (viewMode === "compact") {
    return (
      <div className={`flex items-center gap-4 p-3 hover:bg-gray-50 ${!item.isEnabled ? "opacity-50" : ""}`}>
        <Checkbox checked={isSelected} onCheckedChange={onSelect} />
        <div className="flex-1 min-w-0">
          <p className="font-medium text-sm truncate">Q: {item.question}</p>
        </div>
        <span className="text-xs text-gray-400 hidden sm:block">{categoryName}</span>
        <div className="flex gap-1">
          <button onClick={onEdit} className="p-1 hover:bg-gray-200 rounded">
            <Edit3 className="w-4 h-4 text-gray-500" />
          </button>
          <button onClick={onDelete} className="p-1 hover:bg-gray-200 rounded">
            <Trash2 className="w-4 h-4 text-gray-500" />
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className={`p-6 hover:bg-gray-50 transition-colors group ${!item.isEnabled ? "opacity-50 bg-gray-50" : ""}`}>
      <div className="flex gap-4">
        {/* Left side - drag handle and checkbox */}
        <div className="flex flex-col items-center gap-2">
          <GripVertical className="w-5 h-5 text-gray-300 opacity-0 group-hover:opacity-100 cursor-grab" />
          <Checkbox checked={isSelected} onCheckedChange={onSelect} />
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0">
          {/* Question */}
          <div className="flex items-start justify-between gap-4">
            <p className="font-medium text-gray-900">
              <span className="text-purple-600 font-semibold">Q: </span>
              {item.question}
            </p>

            {/* Actions menu */}
            <div className="relative flex-shrink-0">
              <button
                onClick={() => setShowMenu(!showMenu)}
                className="p-1 hover:bg-gray-200 rounded opacity-0 group-hover:opacity-100"
              >
                <MoreVertical className="w-5 h-5 text-gray-400" />
              </button>

              {showMenu && (
                <>
                  <div className="fixed inset-0 z-10" onClick={() => setShowMenu(false)} />
                  <div className="absolute right-0 top-full mt-1 bg-white rounded-lg border shadow-lg py-1 z-20 min-w-[150px]">
                    <button
                      onClick={() => {
                        onEdit()
                        setShowMenu(false)
                      }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-gray-50 flex items-center gap-2"
                    >
                      <Edit3 className="w-4 h-4" />
                      Edit
                    </button>
                    <button
                      onClick={() => {
                        onDuplicate()
                        setShowMenu(false)
                      }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-gray-50 flex items-center gap-2"
                    >
                      <Copy className="w-4 h-4" />
                      Duplicate
                    </button>
                    <button
                      onClick={() => {
                        onToggleEnabled()
                        setShowMenu(false)
                      }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-gray-50 flex items-center gap-2"
                    >
                      {item.isEnabled ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                      {item.isEnabled ? "Disable" : "Enable"}
                    </button>
                    <button
                      onClick={() => {
                        onDelete()
                        setShowMenu(false)
                      }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-gray-50 flex items-center gap-2 text-red-600"
                    >
                      <Trash2 className="w-4 h-4" />
                      Delete
                    </button>
                  </div>
                </>
              )}
            </div>
          </div>

          {/* Answer */}
          <div className="mt-3">
            <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">
              <span className="text-blue-600 font-semibold">A: </span>
              {item.answer}
            </p>
          </div>

          {/* Tags and actions */}
          <div className="mt-4 flex flex-wrap items-center justify-between gap-2">
            <div className="flex flex-wrap gap-2">
              <span
                className={`text-xs px-2 py-1 rounded-full ${item.isAutoGenerated ? "bg-green-100 text-green-700" : "bg-purple-100 text-purple-700"}`}
              >
                {item.isAutoGenerated ? "Auto-generated" : "Custom"}
              </span>
              <span className="text-xs px-2 py-1 rounded-full bg-gray-100 text-gray-600">{categoryName}</span>
            </div>

            <div className="flex gap-2">
              <Button variant="ghost" size="sm" onClick={onEdit} className="h-8 text-gray-500">
                <Edit3 className="w-4 h-4 mr-1" />
                Edit
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={onDelete}
                className="h-8 text-red-500 hover:text-red-600 hover:bg-red-50"
              >
                <Trash2 className="w-4 h-4 mr-1" />
                Delete
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
